# ChronoTick Inference Configuration - Complete with all sections
# CPU Only with TimesFM 2.5 - Includes clock_measurement and prediction_scheduling

short_term:
  model_name: timesfm
  device: cpu
  enabled: true
  inference_interval: 1.0
  prediction_horizon: 30  # Match scheduler's CPU horizon for proper caching
  context_length: 512  # TimesFM supports up to 2048
  max_uncertainty: 0.1
  model_params:
    prediction_length: 30  # Match scheduler's CPU horizon
    context_length: 512
    model_repo: "google/timesfm-2.5-200m-pytorch"
    backend: "cpu"

long_term:
  model_name: timesfm
  device: cpu
  enabled: true
  inference_interval: 30.0
  prediction_horizon: 60
  context_length: 512  # TimesFM supports up to 2048
  max_uncertainty: 0.15
  model_params:
    prediction_length: 60
    context_length: 512
    model_repo: "google/timesfm-2.5-200m-pytorch"
    backend: "cpu"

fusion:
  enabled: true
  method: inverse_variance
  uncertainty_threshold: 0.05
  fallback_weights:
    short_term: 0.8
    long_term: 0.2

preprocessing:
  outlier_removal:
    enabled: true
    method: iqr
    threshold: 2.0
  missing_value_handling:
    enabled: true
    method: interpolate
  normalization:
    enabled: false
    method: zscore

covariates:
  enabled: true
  variables:
    - cpu_usage
    - temperature
    - memory_usage
  future_variables: []

performance:
  max_memory_mb: 2048
  model_timeout: 10.0
  cache_size: 5
  batch_size: 1

logging:
  level: DEBUG
  log_predictions: true
  log_uncertainty: true
  log_fusion_weights: true

clock:
  frequency_type: second
  frequency_code: 9

# Clock measurement via NTP - Required by ClockMeasurementCollector
clock_measurement:
  ntp:
    servers:
      - pool.ntp.org
      - time.nist.gov
      - time.google.com
    timeout_seconds: 2.0
    max_acceptable_uncertainty: 0.100
    min_stratum: 1
    max_stratum: 16
  timing:
    warm_up:
      duration_seconds: 60
      measurement_interval: 5
    normal_operation:
      measurement_interval: 180

# Prediction scheduling - Required by PredictiveScheduler
prediction_scheduling:
  dataset:
    prediction_cache_size: 100
    max_history_size: 1000
  cpu_model:
    prediction_interval: 5  # Reduced from 1s to reduce GIL contention
    prediction_horizon: 30
    prediction_lead_time: 5
    max_inference_time: 2.0
  gpu_model:
    prediction_interval: 30
    prediction_horizon: 240
    prediction_lead_time: 10
    max_inference_time: 5.0

  # NTP Correction - Blend ML predictions with NTP measurements
  ntp_correction:
    enabled: true  # Enable real-time NTP correction
    method: inverse_variance  # Weighting method: inverse_variance, linear, exponential
    max_ntp_age_seconds: 300  # Don't use NTP measurements older than 5 minutes
    min_ntp_confidence: 0.5  # Minimum confidence to use NTP correction
    # Uncertainty growth rate: how much uncertainty increases per second since NTP
    uncertainty_growth_rate: 0.00001  # 10 Î¼s/s (conservative)
