# ChronoTick Inference Configuration - Hybrid GPU: TimesFM + Toto
# High-performance GPU deployment with complementary models

short_term:
  model_name: toto
  device: cuda
  enabled: true
  inference_interval: 1.0
  prediction_horizon: 8
  context_length: 256
  max_uncertainty: 0.08
  model_params:
    prediction_length: 8
    context_length: 256
    model_size: "base"
    attention_heads: 8

long_term:
  model_name: timesfm
  device: cuda
  enabled: true
  inference_interval: 30.0
  prediction_horizon: 300
  context_length: 1024
  max_uncertainty: 0.10
  model_params:
    context_len: 1024
    horizon_len: 300
    repo: "google/timesfm-2.0-500m-pytorch"
    covariates_enabled: true

fusion:
  enabled: true
  method: inverse_variance
  uncertainty_threshold: 0.035
  fallback_weights:
    short_term: 0.55  # Toto for responsiveness
    long_term: 0.45   # TimesFM for accuracy

preprocessing:
  outlier_removal:
    enabled: true
    method: iqr
    threshold: 1.5
  missing_value_handling:
    enabled: true
    method: interpolate
  normalization:
    enabled: true
    method: zscore

covariates:
  enabled: true
  variables:
    - cpu_usage
    - temperature
    - memory_usage
    - voltage
    - frequency
    - disk_io
    - network_io
  future_variables:
    - temperature
    - cpu_usage

performance:
  max_memory_mb: 10240  # High-end GPU deployment
  model_timeout: 20.0
  cache_size: 25
  batch_size: 12

logging:
  level: INFO
  log_predictions: true
  log_uncertainty: true
  log_fusion_weights: true

clock:
  frequency_type: second
  frequency_code: 9