# ChronoTick Inference Configuration - CPU Only with TTM
# Optimized for TTM (Tiny Time Mixer) models on CPU

short_term:
  model_name: ttm
  device: cpu
  enabled: true
  inference_interval: 1.0
  prediction_horizon: 5
  context_length: 512
  max_uncertainty: 0.1
  model_params:
    prediction_length: 5
    context_length: 512
    patch_length: 16
    num_layers: 3

long_term:
  model_name: ttm
  device: cpu
  enabled: true
  inference_interval: 30.0
  prediction_horizon: 96  # TTM works well with longer horizons
  context_length: 512
  max_uncertainty: 0.12
  model_params:
    prediction_length: 96
    context_length: 512
    patch_length: 16
    num_layers: 3

fusion:
  enabled: true
  method: inverse_variance
  uncertainty_threshold: 0.04
  fallback_weights:
    short_term: 0.7
    long_term: 0.3

preprocessing:
  outlier_removal:
    enabled: true
    method: iqr
    threshold: 1.5
  missing_value_handling:
    enabled: true
    method: interpolate
  normalization:
    enabled: true
    method: zscore

covariates:
  enabled: true
  variables:
    - cpu_usage
    - temperature
    - memory_usage
    - voltage
    - frequency
  future_variables: []

performance:
  max_memory_mb: 1024  # TTM is more memory efficient
  model_timeout: 8.0
  cache_size: 10
  batch_size: 4

logging:
  level: INFO
  log_predictions: true
  log_uncertainty: true
  log_fusion_weights: true

clock:
  frequency_type: second
  frequency_code: 9