# ChronoTick Inference Configuration - Hybrid: Toto (GPU) + Chronos (CPU)
# Efficient GPU+CPU combination: Toto for GPU efficiency, Chronos for CPU speed

short_term:
  model_name: chronos
  device: cpu
  enabled: true
  inference_interval: 1.0
  prediction_horizon: 5
  context_length: 100
  max_uncertainty: 0.1
  model_params:
    prediction_length: 5
    repo: "amazon/chronos-bolt-base"
    size: "base"
    multivariate: true

long_term:
  model_name: toto
  device: cuda
  enabled: true
  inference_interval: 30.0
  prediction_horizon: 96
  context_length: 256
  max_uncertainty: 0.08
  model_params:
    prediction_length: 96
    context_length: 256
    model_size: "base"
    attention_heads: 8

fusion:
  enabled: true
  method: inverse_variance
  uncertainty_threshold: 0.04
  fallback_weights:
    short_term: 0.65  # Chronos excellent for short-term
    long_term: 0.35   # Toto good for medium-term

preprocessing:
  outlier_removal:
    enabled: true
    method: iqr
    threshold: 1.8
  missing_value_handling:
    enabled: true
    method: interpolate
  normalization:
    enabled: true
    method: zscore

covariates:
  enabled: true
  variables:
    - cpu_usage
    - temperature
    - memory_usage
    - voltage
    - frequency
  future_variables: []

performance:
  max_memory_mb: 4096  # Efficient GPU + CPU setup
  model_timeout: 12.0
  cache_size: 12
  batch_size: 6

logging:
  level: INFO
  log_predictions: true
  log_uncertainty: true
  log_fusion_weights: true

clock:
  frequency_type: second
  frequency_code: 9